---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: immich
resources:
- namespace.yaml
- ingressroute.yaml
- postgres.yaml
- pv.yaml
- pvc.yaml
secretGenerator:
- name: postgres-secrets
  envs:
  - .env.postgres
