kind: PersistentVolume
apiVersion: v1
metadata:
  name: immich-volume
spec:
  storageClassName: nfs
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  mountOptions:
    - nfsvers=4.2
  nfs:
    path: "/watermelon-pool/encrypted/immich/immich"
    server: watermelon
