kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: persistence-pv-claim
  namespace: immich
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
