apiVersion: v1
kind: ServiceAccount
metadata:
  name: secret-roles-deployer
  namespace: secret-roles

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secret-roles-deployer
  namespace: secret-roles
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get","patch"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secret-roles-deployer-binding
  namespace: secret-roles
subjects:
  - kind: ServiceAccount
    name: secret-roles-deployer
    namespace: secret-roles
roleRef:
  kind: Role
  name: secret-roles-deployer
  apiGroup: rbac.authorization.k8s.io
