apiVersion: v1
kind: ConfigMap
metadata:
  name: sharry-config
  namespace: sharry
data:
  sharry.conf: |
    sharry.restserver {
      bind {
        address = 0.0.0.0
        port = 9090
      }
      base-url = "https://sharry.blackolivepineapple.pizza"
      backend {
        signup {
          mode = "invite"

          invite-password = ${?SHARRY_INVITE_PASSWORD}

          # If mode == 'invite', this is the period an invitation token is
          # considered valid.
          invite-time = "3 days"
        }
        auth {
          server-secret = ${?SHARRY_SERVER_SECRET}
          fixed {
            enabled = true
            user = "jeff"
            password = ${?ADMIN_PASSWORD}
            order = 10
          }
        }
        jdbc {
          url = "jdbc:postgresql://postgres:5432/sharry"
          user = sharry
          password = ${?POSTGRES_PASSWORD}
        }
      }
    }
