---

- set_fact:
    k3s_master_host: https://raspberry0:6443

- name: Download k3s file from github
  get_url:
    dest: /bin/k3s
    url: https://github.com/k3s-io/k3s/releases/download/v1.28.5%2Bk3s1/k3s-arm64
    owner: root
    group: root
    mode: 0755
  become: yes

- name: Create k3s-agent service directory
  file:
    state: directory
    path: /etc/sv/k3s-agent
  become: yes

- name: Copy run file in k3s-agent service directory
  copy:
    src: run
    dest: /etc/sv/k3s-agent/run
    mode: 0744
  become: yes

- name: Template out conf for k3s-agent service
  template:
    src: conf.j2
    dest: /etc/sv/k3s-agent/conf
    mode: 0600
  become: yes

- name: Create symbolic link
  file:
    src: /etc/sv/k3s-agent
    dest: /var/service/k3s-agent
    state: link
  become: yes



