apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: drone
  name: drone
  namespace: drone
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drone
  template:
    metadata:
      labels:
        app: drone
    spec:
      containers:
      - image: drone/drone
        imagePullPolicy: Always
        name: drone
        ports:
          - containerPort: 443
        env:
          - name: DRONE_GITHUB_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: drone-secrets
                key: DRONE_GITHUB_CLIENT_ID
          - name: DRONE_GITHUB_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: drone-secrets
                key: DRONE_GITHUB_CLIENT_SECRET
          - name: DRONE_RPC_SECRET
            valueFrom:
              secretKeyRef:
                name: drone-secrets
                key: DRONE_RPC_SECRET
          - name: DRONE_SERVER_HOST
            value: drone.blackolivepineapple.pizza
          - name: DRONE_SERVER_PROTO
            value: https
          - name: DRONE_DATABASE_DATASOURCE
            valueFrom:
              secretKeyRef:
                name: drone-secrets
                key: DRONE_DATABASE_DATASOURCE
          - name: DRONE_DATABASE_DRIVER
            value: postgres
          - name: DRONE_USER_CREATE
            value: "username:ToxicGLaDOS,admin:true"
