---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: drone
resources:
- deployment.yaml
- ingressroute.yaml
- namespace.yaml
- postgres.yaml
- pv.yaml
- pvc.yaml
- service.yaml
- runner-deployment.yaml
- runner-rbac.yaml
secretGenerator:
- name: drone-secrets
  envs:
  - .env.drone
- name: postgres-secrets
  envs:
  - .env.postgres
