kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-drone-volume
  namespace: drone
spec:
  storageClassName: nfs
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  mountOptions:
    - nfsvers=4.2
  nfs:
    path: "/watermelon-pool/drone"
    server: watermelon
