---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: umori
resources:
- deployment.yaml
- ingressroute.yaml
- namespace.yaml
- postgres.yaml
- pv.yaml
- pvc.yaml
- service.yaml
secretGenerator:
- name: umori-secrets
  envs:
  - .env.umori
- name: postgres-secrets
  envs:
  - .env.postgres
