kind: PersistentVolume
apiVersion: v1
metadata:
  name: jackett-config-volume
  namespace: jackett
spec:
  storageClassName: nfs
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  mountOptions:
    - nfsvers=4.2
  nfs:
    path: "/watermelon-pool/jackett"
    server: watermelon
