kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jackett-config-claim
  namespace: jackett
spec:
  volumeName: jackett-config-volume
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
