kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: prometheus-pv-claim
  namespace: prometheus
  annotations:
    backup.kubernetes.io/deltas: P1D P7D
spec:
  volumeName: prometheus-volume
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
