apiVersion: v1
kind: ConfigMap
metadata:
  name: cavetown-config
  namespace: cavetown
data:
  blackolivepineapple.pizza.conf: |
    server {
        listen       80;
        listen  [::]:80;
        server_name  cavetown.blackolivepineapple.pizza;

        location / {
            root   /var/www;
            index  index.html;
        }

        #location /play {
        #    root   /var/www/play;
        #    index  cavetown.html;
        #}

        # redirect server error pages to the static page /50x.html
        #
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   /usr/share/nginx/html;
        }
    }
