---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cavetown
resources:
- config-map.yaml
- deployment.yaml
- ingressroute.yaml
- namespace.yaml
- pv.yaml
- pvc.yaml
- service.yaml
