apiVersion: v1
kind: ConfigMap
metadata:
  name: drink-menu-config
  namespace: drink-menu
data:
  blackolivepineapple.pizza.conf: |
    server {
        listen       80;
        listen  [::]:80;
        server_name  menu.blackolivepineapple.pizza;

        location /static/ {
            root   /var/www/;
        }
        location /media/ {
            root   /var/www/;
        }

        error_page  404              /404.html;
        location = /404.html {
            root /var/www/html/;
            internal;
        }
        # redirect server error pages to the static page /50x.html
        #
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   /usr/share/nginx/html;
        }
    }
