---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: drink-menu
resources:
- config-map.yaml
- deployment.yaml
- ingressroute.yaml
- namespace.yaml
- postgres.yaml
- pv.yaml
- pvc.yaml
- service.yaml
secretGenerator:
- name: drink-menu-secrets
  envs:
  - .env.drink-menu
- name: postgres-secrets
  envs:
  - .env.postgres
