kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: grafana-pv-claim
  namespace: grafana
  annotations:
    backup.kubernetes.io/deltas: P1D P7D
spec:
  volumeName: grafana-volume
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
