apiVersion: v1
kind: ConfigMap
metadata:
  name: blackolivepineapple-config
  namespace: blog
data:
  blackolivepineapple.pizza.conf: |
    server {
        listen       80;
        listen  [::]:80;
        server_name  blackolivepineapple.pizza www.blackolivepineapple.pizza;

        location / {
            root   /var/www/blog;
            index  index.html index.htm;
        }

        # redirect server error pages to the static page /50x.html
        #
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   /usr/share/nginx/html;
        }
    }
