apiVersion: v1
kind: ServiceAccount
metadata:
  name: blog-deployer
  namespace: blog

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: blog-deployer
  namespace: blog
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get","patch"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: blog-deployer-binding
  namespace: blog
subjects:
  - kind: ServiceAccount
    name: blog-deployer
    namespace: blog
roleRef:
  kind: Role
  name: blog-deployer
  apiGroup: rbac.authorization.k8s.io
