---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: blog
resources:
- config-map.yaml
- deployment.yaml
- drone-rbac.yaml
- ingressroute.yaml
- namespace.yaml
- service.yaml
