---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kanboard
resources:
- deployment.yaml
- ingressroute.yaml
- namespace.yaml
- postgres.yaml
- pv.yaml
- pvc.yaml
- service.yaml
secretGenerator:
- name: kanboard-secrets
  envs:
  - .env.kanboard
- name: postgres-secrets
  envs:
  - .env.postgres
