kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-kanboard-volume
  namespace: kanboard
spec:
  storageClassName: nfs
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  mountOptions:
    - nfsvers=4.2
  nfs:
    path: "/watermelon-pool/kanboard"
    server: watermelon
